version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: "spring-boot-app"
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=springboot-db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongo-db"
    ports:
      - 27017:27017