version: '3'
services:
  app:
    image: app-image.tar.gz
    ports:
      - 5000:5000
    container_name: "spring-boot-app"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=api
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongo-db"
    ports:
      - 27017:27017